spring:
  application:
    name: Instagram-Clone
  datasource:
    url: jdbc:postgresql://localhost:5432/instagram
    username: postgres
    password: 1224
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
